.PHONY: clean All

All:
	@echo "----------Building project:[ icp_lab3_client - Debug ]----------"
	@cd "icp_lab3_client" && "$(MAKE)" -f  "icp_lab3_client.mk"
clean:
	@echo "----------Cleaning project:[ icp_lab3_client - Debug ]----------"
	@cd "icp_lab3_client" && "$(MAKE)" -f  "icp_lab3_client.mk" clean
