.PHONY: clean All

All:
	@echo "----------Building project:[ ipc_lab3_server - Debug ]----------"
	@cd "ipc_lab3" && "$(MAKE)" -f  "ipc_lab3_server.mk"
clean:
	@echo "----------Cleaning project:[ ipc_lab3_server - Debug ]----------"
	@cd "ipc_lab3" && "$(MAKE)" -f  "ipc_lab3_server.mk" clean
